config/routes.rb
Rails.application.routes.draw do
  resources :reservas
  resources :controllers
  resources :users
    root to: "produtos#index"
    get 'categoria/funkos', controller: 'categoria'

    get "categoria/pelucias"
    get "categoria/figures"
    match 'produtos' => 'produtos#index', via: 'get'
    resources 'produtos', :action => 'show'
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/controller.rb
class Controller < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/models/reserva.rb
class Reserva < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
    def funkos
        @funkos = Produto.where("categoria = ?", "pop funkos")
    end
    def pelucias
        @pelucias = Produto.where("categoria = ?", "pelucias")
    end
    def figures
        @figures = Produto.where("categoria = ?", "action figures")
    end
end

app/controllers/fale_conosco_controller.rb
class FaleConoscoController < ApplicationController
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @reserva = Reserva.new
    
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.fetch(:produto, {})
    end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]

  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.all
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
  end

  # GET /reservas/new
  def new
    @reserva = Reserva.new
  end

  # GET /reservas/1/edit
  def edit
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(reserva_params)
    
  #respond_to do |format|
    if @reserva.save
      UserMailer.with(user: @reserva).send_email.deliver_now
      redirect_to :root
      #UserMailer.with(user: @reserva).send_email.deliver_now
      
      
      #format.html { redirect_to @reserva, notice: 'Reserva was successfully created.' }
      #format.json { render :show, status: :created, location: @reserva }
      
    else
      redirect_to :root
      #format.html { render :new }
      #format.json { render json: @reserva.errors, status: :unprocessable_entity }
    end
    #end
  end

  # PATCH/PUT /reservas/1
  # PATCH/PUT /reservas/1.json
  def update
    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserva }
      else
        format.html { render :edit }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva.destroy
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: 'Reserva was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserva_params
      params.require(:reserva).permit(:email)
    end
end

app/controllers/sobre_controller.rb
class SobreController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def create
    @user = User.new(params[:user])
 
    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.with(user: @user).welcome_email.deliver_now
 
        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end
  # POST /users
  # POST /users.json
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/fale_conosco_helper.rb
module FaleConoscoHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/sobre_helper.rb
module SobreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categoria/figures.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
</head>

<body>
  <!-- Navegação -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

  <!-- Conteudo -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">
        <div class="container">
          <table class="table">
            <thead>
              <tr>
                <th>Minion Store</th>
              </tr>
            </thead>
            <tbody>
              <tr class="active">
                <td><%= active_link_to 'Pelúcias', '/categoria/pelucias' %></td>
              </tr>
        	  <tr class="active">
                <td><%= active_link_to 'Pop Funkos', '/categoria/funkos' %></td>
              </tr>
              <tr class="active">
                <td><%= active_link_to 'Action Figures', '/categoria/figures' %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="col-lg-9">
        <div id="carouselHome" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="https://i.ibb.co/PWdrck7/carroussel1.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://i.ibb.co/PWdrck7/carroussel1.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://i.ibb.co/PWdrck7/carroussel1.jpg" alt="Third slide">
            </div>
          </div>
        </div>
        <div class="row">
        <% @figures.each do |produto| %>
        <% @nome = produto.nome%>
        <% @path = '/produtos/'+produto.id.to_s%>
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="<%= produto.imagem%>" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <%= active_link_to @nome, @path %>
                  
                </h4>
                <h5>Em Breve!</h5>
                <p class="card-text"><%= produto.descricao %></p>
                <% UserMailer.welcome_email.deliver_later%>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9733;</small>
              </div>
            </div>
          </div>
        <% end%>
        
        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Rodapé -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Inventos Digitais</p>
    </div>
    <!-- /.container -->
  </footer>

</body>

</html>

app/views/categoria/funkos.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
</head>

<body>
  <!-- Navegação -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

  <!-- Conteudo -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">
        <div class="container">
          <table class="table">
            <thead>
              <tr>
                <th>Minion Store</th>
              </tr>
            </thead>
            <tbody>
              <tr class="active">
                <td><%= active_link_to 'Pelúcias', '/categoria/pelucias' %></td>
              </tr>
        	  <tr class="active">
                <td><%= active_link_to 'Pop Funkos', '/categoria/funkos' %></td>
              </tr>
              <tr class="active">
                <td><%= active_link_to 'Action Figures', '/categoria/figures' %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="col-lg-9">
        <div id="carouselHome" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="https://i.ibb.co/PWdrck7/carroussel1.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://i.ibb.co/PWdrck7/carroussel1.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://i.ibb.co/PWdrck7/carroussel1.jpg" alt="Third slide">
            </div>
          </div>
        </div>
        <div class="row">
        <% @funkos.each do |produto| %>
        <% @nome = produto.nome%>
        <% @path = '/produtos/'+produto.id.to_s%>
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="<%= produto.imagem%>" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <%= active_link_to @nome, @path %>
                  
                </h4>
                <h5>Em Breve!</h5>
                <p class="card-text"><%= produto.descricao %></p>
                
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9733;</small>
              </div>
            </div>
          </div>
        <% end%>
        
        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Rodapé -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Inventos Digitais</p>
    </div>
    <!-- /.container -->
  </footer>

</body>

</html>

app/views/categoria/pelucias.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
</head>

<body>
  <!-- Navegação -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

  <!-- Conteudo -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">
        <div class="container">
          <table class="table">
            <thead>
              <tr>
                <th>Minion Store</th>
              </tr>
            </thead>
            <tbody>
              <tr class="active">
                <td><%= active_link_to 'Pelúcias', '/categoria/pelucias' %></td>
              </tr>
        	  <tr class="active">
                <td><%= active_link_to 'Pop Funkos', '/categoria/funkos' %></td>
              </tr>
              <tr class="active">
                <td><%= active_link_to 'Action Figures', '/categoria/figures' %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="col-lg-9">
        <div id="carouselHome" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="https://i.ibb.co/PWdrck7/carroussel1.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://i.ibb.co/PWdrck7/carroussel1.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://i.ibb.co/PWdrck7/carroussel1.jpg" alt="Third slide">
            </div>
          </div>
        </div>
        <div class="row">
        <% @pelucias.each do |produto| %>
        <% @nome = produto.nome%>
        <% @path = '/produtos/'+produto.id.to_s%>
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="<%= produto.imagem%>" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <%= active_link_to @nome, @path %>
                  
                </h4>
                <h5>Em Breve!</h5>
                <p class="card-text"><%= produto.descricao %></p>
                
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9733;</small>
              </div>
            </div>
          </div>
        <% end%>
        
        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Rodapé -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Inventos Digitais</p>
    </div>
    <!-- /.container -->
  </footer>

</body>

</html>

app/views/controllers/_form.html.erb
<%= form_with(model: controller, local: true) do |form| %>
  <% if controller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(controller.errors.count, "error") %> prohibited this controller from being saved:</h2>

      <ul>
      <% controller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Produto %>
    <%= form.text_field :Produto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/controllers/edit.html.erb
<h1>Editing Controller</h1>

<%= render 'form', controller: @controller %>

<%= link_to 'Show', @controller %> |
<%= link_to 'Back', controllers_path %>

app/views/controllers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Controllers</h1>

<table>
  <thead>
    <tr>
      <th>Produto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @controllers.each do |controller| %>
      <tr>
        <td><%= controller.Produto %></td>
        <td><%= link_to 'Show', controller %></td>
        <td><%= link_to 'Edit', edit_controller_path(controller) %></td>
        <td><%= link_to 'Destroy', controller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Controller', new_controller_path %>

app/views/controllers/new.html.erb
<h1>New Controller</h1>

<%= render 'form', controller: @controller %>

<%= link_to 'Back', controllers_path %>

app/views/controllers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Produto:</strong>
  <%= @controller.Produto %>
</p>

<%= link_to 'Edit', edit_controller_path(@controller) %> |
<%= link_to 'Back', controllers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  
  <body>
    <%= yield %>
    
  </body>
</html>

app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editing Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app/views/produtos/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
</head>

<body>
  <!-- Navegação -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

  <!-- Conteudo -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">
        <div class="container">
          <table class="table">
            <thead>
              <tr>
                <th>Minion Store</th>
              </tr>
            </thead>
            <tbody>
              <tr class="active">
                <td><%= active_link_to 'Pelúcias', '/categoria/pelucias' %></td>
              </tr>
        	  <tr class="active">
                <td><%= active_link_to 'Pop Funkos', '/categoria/funkos' %></td>
              </tr>
              <tr class="active">
                <td><%= active_link_to 'Action Figures', '/categoria/figures' %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="col-lg-9">
        <div id="carouselHome" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="https://i.ibb.co/PWdrck7/carroussel1.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://i.ibb.co/PWdrck7/carroussel1.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://i.ibb.co/PWdrck7/carroussel1.jpg" alt="Third slide">
            </div>
          </div>
        </div>
        <div class="row">
        <% @produtos.each do |produto| %>
        <% @nome = produto.nome%>
        <% @path = '/produtos/'+produto.id.to_s%>
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="<%= produto.imagem%>" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <%= active_link_to @nome, @path %>
                  
                </h4>
                <h5>Em Breve!</h5>
                <p class="card-text"><%= produto.descricao %></p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9733;</small>
              </div>
            </div>
          </div>
        <% end%>
        
        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Rodapé -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Inventos Digitais</p>
    </div>
    <!-- /.container -->
  </footer>

</body>

</html>

app/views/produtos/new.html.erb
<h1>New Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Back', produtos_path %>

app/views/reservas/_form.html.erb
<%= form_with(model: reserva, local: true) do |form| %>
  <% if reserva.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reserva.errors.count, "error") %> prohibited this reserva from being saved:</h2>

      <ul>
      <% reserva.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservas/edit.html.erb
<h1>Editing Reserva</h1>

<%= render 'form', reserva: @reserva %>

<%= link_to 'Show', @reserva %> |
<%= link_to 'Back', reservas_path %>

app/views/reservas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservas</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= reserva.email %></td>
        <td><%= link_to 'Show', reserva %></td>
        <td><%= link_to 'Edit', edit_reserva_path(reserva) %></td>
        <td><%= link_to 'Destroy', reserva, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reserva', new_reserva_path %>

app/views/reservas/new.html.erb
<h1>New Reserva</h1>

<%= render 'form', reserva: @reserva %>

<%= link_to 'Back', reservas_path %>

app/views/reservas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @reserva.email %>
</p>

<%= link_to 'Edit', edit_reserva_path(@reserva) %> |
<%= link_to 'Back', reservas_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.login %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>